<a href="https://colab.research.google.com/github/DeepakR19/INTERNSOFTcodefiles/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.arange(15).reshape(3,5)
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
  a[a > 4] = 0
  a
  

array([[0, 1, 2, 3, 4],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
a[a > 5] = 3
a

array([[0, 1, 2, 3, 4],
       [5, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [ ]:
a[a == 3] = -1
a

array([[-1,  1,  2, -1,  4],
       [ 5, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1]])

In [ ]:
a == -1

array([[ True, False, False,  True, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [ ]:
   a = np.arange(15).reshape(3,5)
   a[np.logical_and(a > 3, a <= 9)] = 0.0
   a

array([[ 0,  1,  2,  3,  0],
       [ 0,  0,  0,  0,  0],
       [10, 11, 12, 13, 14]])

In [ ]:
a > 4

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True]])

In [ ]:
M = 32
N = 64
xmin = ymin = 0.0
xmax = ymax = 1.0
x = np.linspace(xmin, ymax, M, endpoint=False)
y = np.linspace(xmin, ymax, N, endpoint =False)
print(x.shape)
print(y.shape)
y

(32,)
(64,)


array([0.      , 0.015625, 0.03125 , 0.046875, 0.0625  , 0.078125,
       0.09375 , 0.109375, 0.125   , 0.140625, 0.15625 , 0.171875,
       0.1875  , 0.203125, 0.21875 , 0.234375, 0.25    , 0.265625,
       0.28125 , 0.296875, 0.3125  , 0.328125, 0.34375 , 0.359375,
       0.375   , 0.390625, 0.40625 , 0.421875, 0.4375  , 0.453125,
       0.46875 , 0.484375, 0.5     , 0.515625, 0.53125 , 0.546875,
       0.5625  , 0.578125, 0.59375 , 0.609375, 0.625   , 0.640625,
       0.65625 , 0.671875, 0.6875  , 0.703125, 0.71875 , 0.734375,
       0.75    , 0.765625, 0.78125 , 0.796875, 0.8125  , 0.828125,
       0.84375 , 0.859375, 0.875   , 0.890625, 0.90625 , 0.921875,
       0.9375  , 0.953125, 0.96875 , 0.984375])

In [1]:
import time
import numpy as np 
M = 32
N = 64
x = np.linspace(0.0, 1.0, M, endpoint=False)
y = np.linspace(xmin, 1.0, N, endpoint =False)

In [6]:
t0 = time.time()
g = np.zeros((M,N))
for i in range(M):
  for j in range(N):
    g[i,j] = np.sin(2.0*np.pi*x[i]*y[j])
t1 = time.time()
print("time elapsed: {} s".format(t1-t0))

time elapsed: 0.010575294494628906 s


In [8]:
x2d , y2d = np.meshgrid(x , y, indexing="ij")
print(x2d[:,0])
print(x2d[0,:])
print(y2d[:,0])
print(y2d[0,:])

[0.      0.03125 0.0625  0.09375 0.125   0.15625 0.1875  0.21875 0.25
 0.28125 0.3125  0.34375 0.375   0.40625 0.4375  0.46875 0.5     0.53125
 0.5625  0.59375 0.625   0.65625 0.6875  0.71875 0.75    0.78125 0.8125
 0.84375 0.875   0.90625 0.9375  0.96875]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
[0.       0.015625 0.03125  0.046875 0.0625   0.078125 0.09375  0.109375
 0.125    0.140625 0.15625  0.171875 0.1875   0.203125 0.21875  0.234375
 0.25     0.265625 0.28125  0.296875 0.3125   0.328125 0.34375  0.359375
 0.375    0.390625 0.40625  0.421875 0.4375   0.453125 0.46875  0.484375
 0.5      0.515625 0.53125  0.546875 0.5625   0.578125 0.59375  0.609375
 0.625    0.640625 0.65625  0.671875 0.6875   0.703125 0.71875  0.734375
 0.75     

In [11]:
x = np.array([1, 2, 3, 4])
y = np.array([2, 3, 4, 5])
np.concatenate([y,x])


array([2, 3, 4, 5, 1, 2, 3, 4])

In [12]:
x = [1, 2, 3, 4, 5, 6, 5, 3, 4, 2, 1]
x1, x2, x3, x4 = np.split(x, [3, 5, 6])
print(x1, x2, x3, x4 )

[1 2 3] [4 5] [6] [5 3 4 2 1]


In [14]:
g = np.arange(25).reshape(5,5)
g



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
left, right = np.hsplit(g ,[4])
print(left)
print(right)

[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]
 [15 16 17 18]
 [20 21 22 23]]
[[ 4]
 [ 9]
 [14]
 [19]
 [24]]


In [25]:
x = np.arange(1,9)
print(x)
np.add.reduce(x)

[1 2 3 4 5 6 7 8]


36

In [26]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15, 21, 28, 36])