<a href="https://colab.research.google.com/github/DeepakR19/INTERNSOFTcodefiles/blob/main/numpy_code_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a = np.arange(64)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [ ]:
b = np.arange(40).reshape(20,2)
                          
b
                        

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [ ]:
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(type(b))

2
(20, 2)
40
int64
8
<class 'numpy.ndarray'>


In [ ]:
a = np.array( [1.0, 2.0, 3.0, 4.0] )
print(a)
print(a.dtype)
print(type(a))

[1. 2. 3. 4.]
float64
<class 'numpy.ndarray'>


In [ ]:
c = np.eye(10)
dtype=np.float64
c

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
t = np.linspace(-1, 2, 100, endpoint=True)
print(t)

[-1.         -0.96969697 -0.93939394 -0.90909091 -0.87878788 -0.84848485
 -0.81818182 -0.78787879 -0.75757576 -0.72727273 -0.6969697  -0.66666667
 -0.63636364 -0.60606061 -0.57575758 -0.54545455 -0.51515152 -0.48484848
 -0.45454545 -0.42424242 -0.39393939 -0.36363636 -0.33333333 -0.3030303
 -0.27272727 -0.24242424 -0.21212121 -0.18181818 -0.15151515 -0.12121212
 -0.09090909 -0.06060606 -0.03030303  0.          0.03030303  0.06060606
  0.09090909  0.12121212  0.15151515  0.18181818  0.21212121  0.24242424
  0.27272727  0.3030303   0.33333333  0.36363636  0.39393939  0.42424242
  0.45454545  0.48484848  0.51515152  0.54545455  0.57575758  0.60606061
  0.63636364  0.66666667  0.6969697   0.72727273  0.75757576  0.78787879
  0.81818182  0.84848485  0.87878788  0.90909091  0.93939394  0.96969697
  1.          1.03030303  1.06060606  1.09090909  1.12121212  1.15151515
  1.18181818  1.21212121  1.24242424  1.27272727  1.3030303   1.33333333
  1.36363636  1.39393939  1.42424242  1.45454545  1.

In [ ]:
e = np.logspace(-1, 2, 100, endpoint=True, base=10)
print(e)

[  0.1          0.10722672   0.1149757    0.12328467   0.13219411
   0.14174742   0.15199111   0.16297508   0.17475284   0.18738174
   0.2009233    0.21544347   0.23101297   0.24770764   0.26560878
   0.28480359   0.30538555   0.32745492   0.35111917   0.37649358
   0.40370173   0.43287613   0.46415888   0.49770236   0.53366992
   0.57223677   0.61359073   0.65793322   0.70548023   0.75646333
   0.81113083   0.869749     0.93260335   1.           1.07226722
   1.149757     1.23284674   1.32194115   1.41747416   1.51991108
   1.62975083   1.7475284    1.87381742   2.009233     2.15443469
   2.3101297    2.47707636   2.65608778   2.84803587   3.05385551
   3.27454916   3.51119173   3.76493581   4.03701726   4.32876128
   4.64158883   4.97702356   5.33669923   5.72236766   6.13590727
   6.57933225   7.05480231   7.56463328   8.11130831   8.69749003
   9.32603347  10.          10.72267222  11.49756995  12.32846739
  13.21941148  14.17474163  15.19911083  16.29750835  17.475284
  18.7381742

In [ ]:
f = np.fromfunction(lambda i, j: i == j, (6, 3), dtype=int)
f

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
a = np.arange(90).reshape(30,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]
 [30 31 32]
 [33 34 35]
 [36 37 38]
 [39 40 41]
 [42 43 44]
 [45 46 47]
 [48 49 50]
 [51 52 53]
 [54 55 56]
 [57 58 59]
 [60 61 62]
 [63 64 65]
 [66 67 68]
 [69 70 71]
 [72 73 74]
 [75 76 77]
 [78 79 80]
 [81 82 83]
 [84 85 86]
 [87 88 89]]


In [ ]:
a*3

array([[  0,   3,   6],
       [  9,  12,  15],
       [ 18,  21,  24],
       [ 27,  30,  33],
       [ 36,  39,  42],
       [ 45,  48,  51],
       [ 54,  57,  60],
       [ 63,  66,  69],
       [ 72,  75,  78],
       [ 81,  84,  87],
       [ 90,  93,  96],
       [ 99, 102, 105],
       [108, 111, 114],
       [117, 120, 123],
       [126, 129, 132],
       [135, 138, 141],
       [144, 147, 150],
       [153, 156, 159],
       [162, 165, 168],
       [171, 174, 177],
       [180, 183, 186],
       [189, 192, 195],
       [198, 201, 204],
       [207, 210, 213],
       [216, 219, 222],
       [225, 228, 231],
       [234, 237, 240],
       [243, 246, 249],
       [252, 255, 258],
       [261, 264, 267]])

In [ ]:
a + 5

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22],
       [23, 24, 25],
       [26, 27, 28],
       [29, 30, 31],
       [32, 33, 34],
       [35, 36, 37],
       [38, 39, 40],
       [41, 42, 43],
       [44, 45, 46],
       [47, 48, 49],
       [50, 51, 52],
       [53, 54, 55],
       [56, 57, 58],
       [59, 60, 61],
       [62, 63, 64],
       [65, 66, 67],
       [68, 69, 70],
       [71, 72, 73],
       [74, 75, 76],
       [77, 78, 79],
       [80, 81, 82],
       [83, 84, 85],
       [86, 87, 88],
       [89, 90, 91],
       [92, 93, 94]])

In [ ]:
a*a

array([[   0,    1,    4],
       [   9,   16,   25],
       [  36,   49,   64],
       [  81,  100,  121],
       [ 144,  169,  196],
       [ 225,  256,  289],
       [ 324,  361,  400],
       [ 441,  484,  529],
       [ 576,  625,  676],
       [ 729,  784,  841],
       [ 900,  961, 1024],
       [1089, 1156, 1225],
       [1296, 1369, 1444],
       [1521, 1600, 1681],
       [1764, 1849, 1936],
       [2025, 2116, 2209],
       [2304, 2401, 2500],
       [2601, 2704, 2809],
       [2916, 3025, 3136],
       [3249, 3364, 3481],
       [3600, 3721, 3844],
       [3969, 4096, 4225],
       [4356, 4489, 4624],
       [4761, 4900, 5041],
       [5184, 5329, 5476],
       [5625, 5776, 5929],
       [6084, 6241, 6400],
       [6561, 6724, 6889],
       [7056, 7225, 7396],
       [7569, 7744, 7921]])

In [ ]:
b = a.transpose()
b

array([[ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45,
        48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87],
       [ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46,
        49, 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88],
       [ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47,
        50, 53, 56, 59, 62, 65, 68, 71, 74, 77, 80, 83, 86, 89]])

In [ ]:
a @ b

array([[    5,    14,    23,    32,    41,    50,    59,    68,    77,
           86,    95,   104,   113,   122,   131,   140,   149,   158,
          167,   176,   185,   194,   203,   212,   221,   230,   239,
          248,   257,   266],
       [   14,    50,    86,   122,   158,   194,   230,   266,   302,
          338,   374,   410,   446,   482,   518,   554,   590,   626,
          662,   698,   734,   770,   806,   842,   878,   914,   950,
          986,  1022,  1058],
       [   23,    86,   149,   212,   275,   338,   401,   464,   527,
          590,   653,   716,   779,   842,   905,   968,  1031,  1094,
         1157,  1220,  1283,  1346,  1409,  1472,  1535,  1598,  1661,
         1724,  1787,  1850],
       [   32,   122,   212,   302,   392,   482,   572,   662,   752,
          842,   932,  1022,  1112,  1202,  1292,  1382,  1472,  1562,
         1652,  1742,  1832,  1922,  2012,  2102,  2192,  2282,  2372,
         2462,  2552,  2642],
       [   41,   158,   275,

In [ ]:
print(b)
b.sum(axis=1)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]
 [32 33]
 [34 35]
 [36 37]
 [38 39]]


array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77])

In [ ]:
b.sum()

780

In [ ]:
print(a.max() , a.min())

63 0


In [ ]:
a = a*np.pi/12.0
print(a)

[ 0.          0.26179939  0.52359878  0.78539816  1.04719755  1.30899694
  1.57079633  1.83259571  2.0943951   2.35619449  2.61799388  2.87979327
  3.14159265  3.40339204  3.66519143  3.92699082  4.1887902   4.45058959
  4.71238898  4.97418837  5.23598776  5.49778714  5.75958653  6.02138592
  6.28318531  6.54498469  6.80678408  7.06858347  7.33038286  7.59218225
  7.85398163  8.11578102  8.37758041  8.6393798   8.90117919  9.16297857
  9.42477796  9.68657735  9.94837674 10.21017612 10.47197551 10.7337749
 10.99557429 11.25737368 11.51917306 11.78097245 12.04277184 12.30457123
 12.56637061 12.82817    13.08996939 13.35176878 13.61356817 13.87536755
 14.13716694 14.39896633 14.66076572 14.9225651  15.18436449 15.44616388
 15.70796327 15.96976266 16.23156204 16.49336143]


In [ ]:
c = np.cos(b)
print(c)

[[ 1.          0.54030231]
 [-0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219]
 [ 0.96017029  0.75390225]
 [-0.14550003 -0.91113026]
 [-0.83907153  0.0044257 ]
 [ 0.84385396  0.90744678]
 [ 0.13673722 -0.75968791]
 [-0.95765948 -0.27516334]
 [ 0.66031671  0.98870462]
 [ 0.40808206 -0.54772926]
 [-0.99996083 -0.53283302]
 [ 0.42417901  0.99120281]
 [ 0.64691932 -0.29213881]
 [-0.96260587 -0.74805753]
 [ 0.15425145  0.91474236]
 [ 0.83422336 -0.01327675]
 [-0.84857027 -0.90369221]
 [-0.12796369  0.76541405]
 [ 0.95507364  0.26664293]]


In [ ]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a[4b]

4

In [ ]:
print(a[2:4])

[2 3]


In [2]:
a[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [18]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a[1,2]

7

In [6]:
a[0:3,0:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11]])

In [7]:
a[:,2]

array([ 2,  7, 12])

In [20]:
a = a.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
for i in a:
  print(i)
a = np.arange(15).reshape(3,5)
print(a)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [22]:
for i in a.flat:
  print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [24]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
b = a
b in a

True

In [28]:
b.shape = (2,5)
print(b)
print(a.shape)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [30]:
a = np.arange(15)
b = a[:]
a.shape = (3,5)
print(a)
print(b) 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [32]:
b[1] = -1
print(a)
print(b)

[[ 0 -1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[ 0 -1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [33]:
c = b[3:8]
print(c)

[3 4 5 6 7]


In [34]:
c[:] = 0
print(a)
print(b)
print(c)

[[ 0 -1  2  0  0]
 [ 0  0  0  8  9]
 [10 11 12 13 14]]
[ 0 -1  2  0  0  0  0  0  8  9 10 11 12 13 14]
[0 0 0 0 0]


In [36]:
print(b is a)
print(b.base is a)
print(b.flags.owndata)
print(a.flags.owndata)

False
True
False
True


In [37]:
c = a.copy()
c[:,:] = 0.0
print(a)
print(c)

[[ 0 -1  2  0  0]
 [ 0  0  0  8  9]
 [10 11 12 13 14]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
